export const ACTIVITY_TYPE_LABELS = {
  TICKET_CREATED: "Ticket creado",
  REVIEW_STARTED: "Análisis iniciado",
  STATE_CHANGED: "Estado actualizado",
  REQUEST_TYPE_CHANGED: "Clasificación corregida",
  ROUTED: "Derivado al área",
  RETURNED_BY_AREA: "Devuelto por el área",
  PRIORITY_CHANGED: "Prioridad actualizada",
  SLA_NEAR_DUE: "SLA próximo a vencer",
  SLA_BREACHED: "SLA vencido",
  ESCALATED: "Ticket escalado",
  INFORMATION_REQUIRED: "Información solicitada al ciudadano",
  INFORMATION_PROVIDED: "El ciudadano respondió",
  PROGRESS_REPORTED: "Progreso informado por el área",
  DUPLICATE_LINKED: "Vinculado como duplicado",
  RESOLVED: "Ticket resuelto",
  REOPENED: "Ticket reabierto",
  CANCELLATION_REQUESTED: "Cancelación solicitada",
  CANCELLATION_APPROVED: "Cancelación aprobada",
  CANCELLATION_REJECTED: "Cancelación rechazada",
  CANCELLED: "Ticket cancelado",
  CLOSED: "Ticket cerrado",
  PUBLIC_MESSAGE_SENT: "Mensaje enviado al ciudadano",
  INTERNAL_MESSAGE_ADDED: "Nota interna agregada",
  ATTACHMENT_ADDED: "Adjunto agregado",
};
